"""initial migrations

Revision ID: 730562713315
Revises: 
Create Date: 2021-09-29 15:37:32.746734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730562713315'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('songName', sa.String(length=100), nullable=True),
    sa.Column('artistName', sa.String(length=50), nullable=True),
    sa.Column('songDuration', sa.Integer(), nullable=True),
    sa.Column('songType', sa.String(length=50), nullable=True),
    sa.Column('songDescription', sa.String(length=100), nullable=True),
    sa.Column('songQuality', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('songName')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=250), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('audio')
    # ### end Alembic commands ###
